# Generated by Django 3.0.3 on 2020-04-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=64)),
                ('Lname', models.CharField(max_length=64)),
                ('Email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
